package siemcenterrules.rules;

import java.util.List;
import java.time.LocalDateTime;
import com.securityoperationscenter.siemcenter.model.Account;
import com.securityoperationscenter.siemcenter.model.RiskLevel;
import com.securityoperationscenter.siemcenter.model.Alarm;
import com.securityoperationscenter.siemcenter.model.Log;
import com.securityoperationscenter.siemcenter.model.ErrorLog;
import com.securityoperationscenter.siemcenter.model.LoginLog;
import com.securityoperationscenter.siemcenter.model.PaymentLog;
import com.securityoperationscenter.siemcenter.model.AntivirusThreatDetectionLog;

global List maliciousIpAddresses;

rule "Detect when ErrorLog appears"
    when
       ErrorLog()
    then
      System.out.println("RULE FIRED: Detect when ErrorLog appears.");
end

rule "Detect malicious ip address"
    when
        Log(machine.ip memberOf maliciousIpAddresses)
    then
        System.out.println("RULE FIRED: Detect malicious ip address.");
end

rule "Fire payment system alarm"
    when
        $log: PaymentLog($username: username, $timestamp: timestamp)

        Number(intValue > 50) from accumulate(
            $paymentLogs: PaymentLog(
                username == $username,
                over window: time(60s),
            ),
            count($paymentLogs)
        )
    then
        insert (
            new Alarm(
                "PAYMENT",
                "Payment system alarm!",
                $username,
                LocalDateTime.now()
            )
        );
end

rule "Set account risk level to low when no alarm in past 90 days"
   no-loop
   when
       $account: Account($username: username)

       Number(intValue = 0) from accumulate(
            Alarm(
               username == $username,
               over window: time(90d),
            )
       )
   then
       modify($account) {
           setRiskLevel(RiskLevel.LOW);
       }

       System.out.println("RULE FIRED: Set account risk level to low when no alarm in past 90 days for user: " + $username + ".");
end
